### ISSUE TITLE
<%= yield(:title) -%> should not yield body

### ISSUE THREAD

**Issue by jochend** [oggy/template_streaming#2]
If I have this in my pre/application.html.erb : <head><title><%= yield :title %></title></head><%= yield %>
then it should not yield in the title tag...

Nice plugin btw :) testing it with nginx + passenger

**Comment by oggy** [comment]
Hi jochend,

Thanks for the report. I haven't been able to reproduce this, though perhaps I'm misunderstanding. Below is what I tried.

Note that unlike the layout, the prelayout is evaluated before the main view template, so I'm not sure how helpful a "yield :title" would be in the prelayout.

```
g@zoom:~/tstest [master] $ cat config/routes.rb 
ActionController::Routing::Routes.draw do |map|
  map.root :controller => 'home', :action => 'index'
end

g@zoom:~/tstest [master] $ cat app/controllers/home_controller.rb 
class HomeController < ApplicationController
  def index
  end
end

g@zoom:~/tstest [master] $ cat app/views/prelayouts/application.html.erb 
<% content_for :title do %>
  TITLE
<% end %>
<%= yield :title %>
<%= yield %>

g@zoom:~/tstest [master] $ cat app/views/layouts/application.html.erb 
[
<%= yield %>
]

g@zoom:~/tstest [master] $ cat app/views/home/index.html.erb 
(content)
```
