### ISSUE TITLE
rails 2.2.2 how to make it work?

### ISSUE THREAD

**Issue by dashbitla** [oggy/template_streaming#3]
Am not able to use this plugin in rails 2.2.2 version.... its failing with the following error:

Is there a way to make it work - please help.

D:/work/ticketsimply-trunk/vendor/rails/activesupport/lib/active_support/dependencies.rb:442:in `load_missing_constant':
 uninitialized constant ActionController::Response (NameError)
        from D:/work/ticketsimply-trunk/vendor/rails/activesupport/lib/active_support/dependencies.rb:77:in`const_missi
ng'
        from D:/work/ticketsimply-trunk/vendor/plugins/template_streaming/lib/template_streaming.rb:305
        from D:/s/InstantRails/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from D:/s/InstantRails/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from D:/work/ticketsimply-trunk/vendor/rails/activesupport/lib/active_support/dependencies.rb:153:in `require'
        from D:/work/ticketsimply-trunk/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in`new_consta
nts_in'
        from D:/work/ticketsimply-trunk/vendor/rails/activesupport/lib/active_support/dependencies.rb:153:in `require'
        from D:/work/ticketsimply-trunk/vendor/plugins/template_streaming/rails/init.rb:1:in`evaluate_init_rb'
         ... 38 levels...
        from D:/work/ticketsimply-trunk/vendor/rails/railties/lib/commands/server.rb:49
        from D:/s/InstantRails/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from D:/s/InstantRails/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from script/server:3

**Comment by oggy** [comment]
Hi dashbitla,

I have only been using it with 2.3.

I have no current plans to add 2.2 support myself. I want to focus
more on finishing 2.3 support, adding 3.0 support, and then adding the
proposed 3.1 features.

If you can provide a patch for 2.2 which doesn't add too much
complexity to the codebase, I would be happy to merge it in.
