### ISSUE TITLE
undefined method `_render_with_layout'

### ISSUE THREAD

**Issue by stefanwille** [oggy/template_streaming#4]
Hey,

I tried your gem on a Rails 3 application with Ruby 1.9.2. Is this supposed to work?
I get this:

stefan@ip-192-168-1-16 Prototype (master)$ rails server
/Users/stefan/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.0/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method': undefined method`_render_with_layout' for class `ActionView::Base' (NameError)
        from /Users/stefan/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.0/lib/active_support/core_ext/module/aliasing.rb:31:in`alias_method_chain'
        from /Users/stefan/.rvm/gems/ruby-1.9.2-p0/gems/template_streaming-0.0.11/lib/template_streaming.rb:199:in `included'
        from /Users/stefan/.rvm/gems/ruby-1.9.2-p0/gems/template_streaming-0.0.11/lib/template_streaming.rb:278:in`include'
        from /Users/stefan/.rvm/gems/ruby-1.9.2-p0/gems/template_streaming-0.0.11/lib/template_streaming.rb:278:in `<module:TemplateStreaming>'
        from /Users/stefan/.rvm/gems/ruby-1.9.2-p0/gems/template_streaming-0.0.11/lib/template_streaming.rb:1:in`<top (required)>'
        from /Users/stefan/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.0/lib/bundler/runtime.rb:64:in `require'
        from /Users/stefan/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.0/lib/bundler/runtime.rb:64:in`block (2 levels) in require'
        from /Users/stefan/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.0/lib/bundler/runtime.rb:62:in `each'
        from /Users/stefan/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.0/lib/bundler/runtime.rb:62:in`block in require'
        from /Users/stefan/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.0/lib/bundler/runtime.rb:51:in `each'
        from /Users/stefan/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.0/lib/bundler/runtime.rb:51:in`require'
        from /Users/stefan/.rvm/gems/ruby-1.9.2-p0/gems/bundler-1.0.0/lib/bundler.rb:112:in `require'

Cheers,
Stefan

**Comment by oggy** [comment]
Hi Stefan,

There is no Rails 3 support yet. To come soon.

**Comment by stefanwille** [comment]
Thanks

**Comment by jarinudom** [comment]
Rails 3.1 is doing this anyway, so probably no point in making it work with Rails 3.
