### ISSUE TITLE
Unable to use this with Rails v3.2.14

### ISSUE THREAD

**Issue by akshayakrsh** [oggy/template_streaming#9]
Hi,

I am unable to use your gem with Rails v3.2.14 and Ruby v2.0.0p247. Below is the error I get when I try to run my server. I also tried forking your repository and update the active_support version in the GemFile and gemspec files and use my github repo directly for the gem but the same error was shown again.

/home/akshaya/.rvm/gems/ruby-2.0.0-p247@insta_engine_app/gems/activesupport-3.2.14/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method': undefined method`_render_with_layout' for class `ActionView::Base' (NameError)
    from /home/akshaya/.rvm/gems/ruby-2.0.0-p247@insta_engine_app/gems/activesupport-3.2.14/lib/active_support/core_ext/module/aliasing.rb:31:in`alias_method_chain'
    from /home/akshaya/.rvm/gems/ruby-2.0.0-p247@insta_engine_app/bundler/gems/template_streaming-347f338eeb4b/lib/template_streaming.rb:237:in `included'
    from /home/akshaya/.rvm/gems/ruby-2.0.0-p247@insta_engine_app/bundler/gems/template_streaming-347f338eeb4b/lib/template_streaming.rb:357:in`include'
    from /home/akshaya/.rvm/gems/ruby-2.0.0-p247@insta_engine_app/bundler/gems/template_streaming-347f338eeb4b/lib/template_streaming.rb:357:in `<module:TemplateStreaming>'
    from /home/akshaya/.rvm/gems/ruby-2.0.0-p247@insta_engine_app/bundler/gems/template_streaming-347f338eeb4b/lib/template_streaming.rb:1:in`<top (required)>'
    from /home/akshaya/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
    from /home/akshaya/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in`block (2 levels) in require'
    from /home/akshaya/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
    from /home/akshaya/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in`block in require'
    from /home/akshaya/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
    from /home/akshaya/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in`require'
    from /home/akshaya/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
    from /home/akshaya/Development/insta_engine_app/config/application.rb:7:in`<top (required)>'
    from /home/akshaya/.rvm/gems/ruby-2.0.0-p247@insta_engine_app/gems/railties-3.2.14/lib/rails/commands.rb:53:in `require'
    from /home/akshaya/.rvm/gems/ruby-2.0.0-p247@insta_engine_app/gems/railties-3.2.14/lib/rails/commands.rb:53:in`block in <top (required)>'
    from /home/akshaya/.rvm/gems/ruby-2.0.0-p247@insta_engine_app/gems/railties-3.2.14/lib/rails/commands.rb:50:in `tap'
    from /home/akshaya/.rvm/gems/ruby-2.0.0-p247@insta_engine_app/gems/railties-3.2.14/lib/rails/commands.rb:50:in`<top (required)>'
    from /home/akshaya/Development/insta_engine_app/script/rails:6:in `require'
    from /home/akshaya/Development/insta_engine_app/script/rails:6:in`<top (required)>'
    from -e:1:in `load'
    from -e:1:in`<main>'

**Comment by oggy** [comment]
As per the README, this plugin is for Rails 2.x. Rails 3 and above ship with a varying amount of support for streaming. See [this screen](http://railscasts.com/episodes/266-http-streaming) for example.
